#### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [67]:
lst = [20,30,12,34,56]

In [68]:
lst.append(49)

In [69]:
lst

[20, 30, 12, 34, 56, 49]

In [70]:
lst.extend([10,15,43])

In [71]:
lst

[20, 30, 12, 34, 56, 49, 10, 15, 43]

In [72]:
lst.insert(3,12)

In [73]:
lst

[20, 30, 12, 12, 34, 56, 49, 10, 15, 43]

In [74]:
lst.remove(34)

In [75]:
lst

[20, 30, 12, 12, 56, 49, 10, 15, 43]

In [76]:
lst.pop(5)

49

In [77]:
lst.clear()

In [78]:
lst

[]

In [79]:
lst = [20, 30, 12, 12, 34, 56, 49, 10, 15, 43]

In [80]:
lst.index(34)

4

In [81]:
lst.count(12)

2

In [82]:
lst.sort()
lst

[10, 12, 12, 15, 20, 30, 34, 43, 49, 56]

In [83]:
lst.sort(reverse=True)
lst

[56, 49, 43, 34, 30, 20, 15, 12, 12, 10]

#### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [84]:
students = ('Muad','Savin','Ajin')

In [85]:
students

('Muad', 'Savin', 'Ajin')

In [86]:
type(students)

tuple

In [87]:
students[1] = 'Amal'

TypeError: 'tuple' object does not support item assignment

#### Tuples in Python are immutable data structures. once a tuple is created, it cannot be change, add or remove

#### 3.	Create a set of integers with some duplicate values. Print the set and explain the output

In [88]:
lst = [2,4,1,2,3,1,6]
l_set = set(lst)
l_set

{1, 2, 3, 4, 6}

#### The lst containing duplicate values (1, 2 appear more than once) is converted into a set, the set automatically eliminates these duplicates, retaining only one instance of each distinct integer

#### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [90]:
d1 = { 
    'Name' : 'Vighnesh',
    'Age' : 22,
    'City' : 'Kollam'
}

In [91]:
d1

{'Name': 'Vighnesh', 'Age': 22, 'City': 'Kollam'}

In [105]:
d2 = {
    'Age':23,
    'Email':'vighneshr2063@gmail.com'
}

In [106]:
d1.update(d2)

In [107]:
d1

{'Name': 'Vighnesh',
 'Age': 23,
 'City': 'Kollam',
 'Email': 'vighneshr2063@gmail.com'}

#### 5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [111]:
Age = int(input('Please Enter Your Age:'))

if Age >= 18:
    print('You Are Eligible To Vote')
else:
    print('Sorry')
    print('You Are Not Eligible')

Please Enter Your Age: 18


You Are Eligible To Vote


#### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [118]:
Mark = int(input('Enter Your Mark:'))

if Mark >= 90:
    print('A grade')
elif Mark >=75 and Mark <90:
    print('B grade')
elif Mark >=50 and Mark <75:
    print('C grade')
else:
    print('FAIL')

Enter Your Mark: 49


FAIL


#### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [122]:
def check_number_properties(num):
    if num>0:
        if num%2 == 0:
            print(f'{num} is a postive and a even number')
        else:
            print(f'{num} is a postive number')
    elif num == 0:
        print(f'{num} is zero')
    else:
        print(f'{num} is negative')

In [123]:
check_number_properties(4)

4 is a postive and a even number


In [124]:
check_number_properties(3)

3 is a postive number


In [125]:
check_number_properties(0)

0 is zero


In [126]:
check_number_properties(-3)

-3 is negative


## Section B: Numpy

#### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [140]:
import numpy as np

scalar = np.array(5)
print('Scalar:', scalar)
print('Scalar dimension:', scalar.ndim)

one_d_array = np.arange(1, 6) 
print('1D Array:', one_d_array)
print('1D Array dimension:', one_d_array.ndim)

two_d_array = np.arange(10, 70, 10).reshape(2,3)
print('2D Array:\n', two_d_array)
print('2D Array dimension:', two_d_array.ndim)

Scalar: 5
Scalar dimension: 0
1D Array: [1 2 3 4 5]
1D Array dimension: 1
2D Array:
 [[10 20 30]
 [40 50 60]]
2D Array dimension: 2


#### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [163]:
import numpy as np
randm_array = np.random.randint(0,100,size=(4,4))
randm_array

array([[34, 75, 72, 38],
       [ 8, 79, 36, 93],
       [91, 53, 40, 32],
       [96, 58, 43, 28]], dtype=int32)

#### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [164]:
import numpy as np
import pandas as pd

In [167]:
two_d_array = np.array([[12,32,24],[13,43,45],[16,32,22]])
two_d_array

array([[12, 32, 24],
       [13, 43, 45],
       [16, 32, 22]])

In [168]:
pd.DataFrame(two_d_array,columns=['A','B','C'])

A   B   C
0  12  32  24
1  13  43  45
2  16  32  22

## Section C: Exploring Pandas

#### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [232]:
data = [
    ['Vighnesh',22,'Kollam',25000],
    ['Savin',22,'Kollam',30000],
    ['Ajin',23,'TVM',28000],
    ['Anzil',24,'Kottayam',25000],
    ['Adith',22,'TVM'],
    ['Vipin',23,'Kollam',22000],
    ['Muad',22,'EKM',23000],
    ['Rishad',24,'Kannur',25000],
    ['Anzil',24,'Kottayam',25000],
    ['Ameen',23,'Kollam',22000]
]

In [233]:
col_name = ['Name','Age','City','Salary']

In [234]:
df = pd.DataFrame(data,columns=col_name)
df

Name  Age      City   Salary
0  Vighnesh   22    Kollam  25000.0
1     Savin   22    Kollam  30000.0
2      Ajin   23       TVM  28000.0
3     Anzil   24  Kottayam  25000.0
4     Adith   22       TVM      NaN
5     Vipin   23    Kollam  22000.0
6      Muad   22       EKM  23000.0
7    Rishad   24    Kannur  25000.0
8     Anzil   24  Kottayam  25000.0
9     Ameen   23    Kollam  22000.0

In [235]:
df2 = df.copy()

In [236]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [237]:
df.describe()

Age        Salary
count  10.000000      9.000000
mean   22.900000  25000.000000
std     0.875595   2645.751311
min    22.000000  22000.000000
25%    22.000000  23000.000000
50%    23.000000  25000.000000
75%    23.750000  25000.000000
max    24.000000  30000.000000

In [238]:
df.loc[:,['Name','City']]

Name      City
0  Vighnesh    Kollam
1     Savin    Kollam
2      Ajin       TVM
3     Anzil  Kottayam
4     Adith       TVM
5     Vipin    Kollam
6      Muad       EKM
7    Rishad    Kannur
8     Anzil  Kottayam
9     Ameen    Kollam

In [239]:
df.drop('City',axis=1,inplace=True)
df

Name  Age   Salary
0  Vighnesh   22  25000.0
1     Savin   22  30000.0
2      Ajin   23  28000.0
3     Anzil   24  25000.0
4     Adith   22      NaN
5     Vipin   23  22000.0
6      Muad   22  23000.0
7    Rishad   24  25000.0
8     Anzil   24  25000.0
9     Ameen   23  22000.0

In [240]:
mean_salry = df2['Salary'].mean()
mean_salry

np.float64(25000.0)

In [241]:
df2['Salary'].fillna(mean_salry,inplace=True)

C:\Users\vighn\AppData\Local\Temp\ipykernel_3892\3545359057.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Salary'].fillna(mean_salry,inplace=True)


In [242]:
df2

Name  Age      City   Salary
0  Vighnesh   22    Kollam  25000.0
1     Savin   22    Kollam  30000.0
2      Ajin   23       TVM  28000.0
3     Anzil   24  Kottayam  25000.0
4     Adith   22       TVM  25000.0
5     Vipin   23    Kollam  22000.0
6      Muad   22       EKM  23000.0
7    Rishad   24    Kannur  25000.0
8     Anzil   24  Kottayam  25000.0
9     Ameen   23    Kollam  22000.0

In [245]:
df2.drop_duplicates(inplace=True)
df2

Name  Age      City   Salary
0  Vighnesh   22    Kollam  25000.0
1     Savin   22    Kollam  30000.0
2      Ajin   23       TVM  28000.0
3     Anzil   24  Kottayam  25000.0
4     Adith   22       TVM  25000.0
5     Vipin   23    Kollam  22000.0
6      Muad   22       EKM  23000.0
7    Rishad   24    Kannur  25000.0
9     Ameen   23    Kollam  22000.0